language: r
r:
  - oldrel
  - release
cache: packages
warnings_are_errors: true
sudo: required
r_github_packages:
  - swihart/lasagnar
r_packages:
  - covr
after_success:
  - Rscript -e 'library(covr); codecov()'
